print("=== Pruebas de Operaciones con Matrices ===")
let A = matrix([[1, 2], [3, 4]])
let B = matrix([[5, 6], [7, 8]])
let C = A.add(B)
let D = A.multiply(B)
let E = A.transpose()
print(C)
print(D)
print(E)
